In [73]:
import pandas as pd

data_dict = {
    'a': [1, 2, 3],
    'b': [4, 5, 6]
}

dat = pd.DataFrame(data_dict)
dat

   a  b
0  1  4
1  2  5
2  3  6

In [74]:
data_list = [
    {'a': 1, 'b': 4},
    {'a': 2, 'b': 5},
    {'a': 3, 'b': 6}
]

dat2 = pd.DataFrame(data_list)
dat2

   a  b
0  1  4
1  2  5
2  3  6

In [75]:
dat.head(1)

   a  b
0  1  4

In [76]:
dat.tail(1)

   a  b
2  3  6

In [77]:
dat['a']

0    1
1    2
2    3
Name: a, dtype: int64

In [78]:
dat.loc[0]

a    1
b    4
Name: 0, dtype: int64

In [79]:
dat.iloc[0]

a    1
b    4
Name: 0, dtype: int64

In [80]:
dat.index

RangeIndex(start=0, stop=3, step=1)

In [81]:
dat[['a', 'b']]

   a  b
0  1  4
1  2  5
2  3  6

In [82]:
dat[dat['a'] > 2]

   a  b
2  3  6

In [83]:
dat[dat['a'] > 2]['a']

2    3
Name: a, dtype: int64

In [84]:
dat.to_csv("data_example.csv", index=False)

### Murray (2017) Chapter 1 Response

**What does the “write/render/evaluate” loop provide for creators of interactive data visualizations?**

The write/render/evaluate loop allows creators to quickly experiment with different visual mappings and see the results immediately. This kind of rapid feedback supports iteration which also helps designers refine their visualizations efficiently. This then helps improve clarity, accuracy, and aesthetic decisions without starting from scratch each time.

**Why are dynamic, interactive data visualizations useful when communicating data?**

Dynamic, interactive visualizations help users to explore data at multiple levels by zooming, filtering, and accessing details on demand. This makes complex or even multidimensional datasets more accessible to diverse audiences, considering both casual exploration and targeted analysis while also increasing engagement.

**Do you agree with Murray’s claim that open-source tools that avoid proprietary software are best for publishing data visualization?**

Yes, I agree. I believe that open-source, web-standard tools that avoid proprietary software are best for publishing data visualization because they increase accessibility by allowing visualizations to be viewed across devices and operating systems without requiring specialized software. They also promote longevity, transparency, and even wider reach, ensuring that visualizations remain usable and shareable over time.